apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: glyph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: glyph/auth:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: auth-secrets
            - configMapRef:
                name: auth-config
          ports:
            - containerPort: 50051
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
