apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pvc
  namespace: glyph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
