apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: glyph
data:
  ORDER_SVC_PORT: ":50055"
  METRICS_PORT: ":9100"

  ORDER_DB: order_db
  ORDER_DB_USER: order-db-user
  ORDER_DB_PASSWORD: orderpassword
  ORDER_DB_PORT: "5432"
  ORDER_DB_HOST: orderdb.glyph.svc.cluster.local

  ORDERBK_SVC_PORT: "order-book:50056"

  USER_SVC_PORT: "user:50053"

  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.glyph.svc.cluster.local:5672/%2f"
