apiVersion: v1
kind: Service
metadata:
  name: order-book
  namespace: glyph
spec:
  selector:
    app: order-book
  ports:
    - name: grpc
      protocol: TCP
      port: 50056
      targetPort: 50056
  type: ClusterIP
