apiVersion: v1
kind: ConfigMap
metadata:
  name: order-book-config
  namespace: glyph
data:
  SERVER_HOST: "[::]"
  SERVER_PORT: "50056"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.glyph.svc.cluster.local:5672/%2f"
