apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: glyph
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
