apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: glyph
data:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_ERLANG_COOKIE: glyphrabbitmqdemocookie0001
