apiVersion: v1
kind: ConfigMap
metadata:
  name: advisor-config
  namespace: glyph
data:
  ADVISOR_SVC_PORT: ":50058"
  METRICS_PORT: ":9100"

  USER_SVC_PORT: "user:50053"
  INFERENCE_SVC_PORT: "inference:50057"
  STRATEGY_SVC_PORT: "strategy:50059"

  LLM_PROVIDER: "gemini"
  GEMINI_MODEL: "gemini-2.5-flash"

  CACHE_ADDR: "auth-cache:6379"
