apiVersion: v1
kind: ConfigMap
metadata:
  name: advisor-config
  namespace: glyph
data:
  ADVISOR_SVC_PORT: ":50058"
  METRICS_PORT: ":9100"

  USER_SVC_PORT: "user:50053"
  INFERENCE_SVC_PORT: "inference:50057"

  CACHE_ADDR: "auth-cache:6379"
