apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-models-pvc
  namespace: glyph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
