apiVersion: v1
kind: PersistentVolume
metadata:
  name: inference-models-volume
  labels:
    app: inference
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  claimRef:
    name: inference-models-pvc
    namespace: glyph
  hostPath:
    path: /Users/yashgadgil/Documents/Projects/glyph/.data/inference-models
    type: DirectoryOrCreate
